# This is a basic workflow to help you get started with Actions

name: Update OG ID

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 3 * * *'
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          SSH_PUBKEY: ${{ secrets.SSH_KEY_PUB  }}
          SSH_PRIVATEKEY: ${{ secrets.SSH_KEY_RSA }}
        run: |
          chmod +x ci-build.sh
          ./ci-build.sh
